apiVersion: v1
kind: PersistentVolume
metadata:
  name: flexdirect-licenses
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.6.144
    path: "/srv/exports"
