apiVersion: v1
kind: Service
metadata:
  name: tokenmgr
  labels:
    app.kubernetes.io/name: tokenmgr
    app.kubernetes.io/instance: tokenmgr
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: tokenmgr
      protocol: TCP
      name: tokenmgr
  selector:
    #app.kubernetes.io/name: tokenmgr
    #app.kubernetes.io/instance: tokenmgr
    app: tokenmgr
